### ISSUE TITLE
Support for fat32 or other file systems?

### ISSUE THREAD

**Issue by changhenry2** [master-hax/pixel-backup-gang#23]
Hi, I've read the readme file and understood that the project currently only support ext4 file system.

Is there any plan to support fat32 or other file systems?

I believe it will be more helpful since Windows and Android natively supports fat32 file system.

Thanks!

**Comment by master-hax** [comment]
since fat32 drives are supported & mounted by the OS, we would probably want to build on the existing mounting process

i think that code is here: https://chromium.googlesource.com/aosp/platform/system/core/+/upstream/sdcard/sdcard.cpp

**Comment by changhenry2** [comment]
Thanks! If fat32 is supported, I would like to transfer the photos from Android phone to pixel phone via usb flash drive.

**Comment by master-hax** [comment]
@changhenry2 i made a script to remount vfat drives - give it a try: [remount_vfat.sh](https://github.com/master-hax/pixel-backup-gang/blob/c2a62f1421a4b95b549b5e6e00391eabe01bb4ca/scripts/remount_vfat.sh)

**Comment by master-hax** [comment]
i merged it into the repo: https://github.com/master-hax/pixel-backup-gang/blob/4bac00e49ee460964c004129201f113112bccdda/scripts/remount_vfat.sh

**Comment by master-hax** [comment]
closing this issue since i merged a solution & haven't heard back in a while. feel free to reopen it if the new script doesn't work.

**Comment by RoboCrafty** [comment]
Reopening this since I’m having issues using FAT32 drives. (I can’t try EXT4 as I primarily use windows atm)

Please note that I’m not running this on a pixel but on different android device running a custom rom which spoofs this device as a pixel. I’ve already backed up over 600 gigs by copying it over to the device. 

Please see the attached screenshots. After running the remount_vfat script it just shows this: 
detected filesystem type was not "msdos", found vfat


![IMG_3231](https://github.com/user-attachments/assets/a167e829-38bf-431c-9cf9-eb56f5bc0f57)
![IMG_3230](https://github.com/user-attachments/assets/770d91e8-4010-4e8e-ada8-83e312a5185c)

**Comment by RoboCrafty** [comment]
Update:

I fixed it by commenting out the "exit 1" line after the last if condiition. But now I faced a different issue. Making a new issue for that.


> if [ "$fs_type" != "msdos" ]; then
    echo "detected filesystem type was not 'msdos', found $fs_type"
    # exit 1
fi
>
